language: php
php:
  - '7.4'
  - '7.3'
  - '7.2'
  - '7.1'
  - '7.0'
  - '5.6'
  - hhvm
matrix:
  exclude:
    - php: hhvm
      env: ENABLE_REDIS_EXT=1
  allow_failures:
    - php: '7.4'
    - php: '7.3'
    - php: '7.2'
    - php: hhvm
env:
  - ENABLE_REDIS_EXT=0
  - ENABLE_REDIS_EXT=1
before_script:
  - sh -c "if [ $ENABLE_REDIS_EXT -eq 1 ]; then echo \"extension=redis.so\" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi"
  - composer install
